### ISSUE TITLE
Plugin not working on large strings

### ISSUE THREAD

**Issue by Djalmar** [saintedlama/mongoose-version#26]
I have this model 

```
'use strict';

import mongoose from 'mongoose';
import version from 'mongoose-version';
import AutoIncrement from 'mongoose-sequence';
const sequence = AutoIncrement(mongoose);
import {
  registerEvents
} from './solicitud.events';
var SolicitudSchema = new mongoose.Schema({
  antecedentes: {
    type: String,
    default: ''
  },
  usos: {
    type: String,
    default: ''
  },
  alternativa: {
    type: String,
    default: ''
  },
  justificacion: {
    type: String,
    default: ''
  },
  __machina__: {
    type: {},
    default: {}
  },
  numero: Number
});

registerEvents(SolicitudSchema);
SolicitudSchema.plugin(version, {
  mongoose
});
SolicitudSchema.plugin(sequence, {
  inc_field: 'numero'
});

export default mongoose.model('Solicitud', SolicitudSchema);
```

When any of the String fields is more than 1500 characters on save() no new version is saved, also versioning stops working for that document no mater if you change other field

Sorry for the bad English

**Comment by yitomok** [comment]
@Djalmar What is your MongoDB setting? Did you exceed the maximum JSON object size?

**Comment by tomercagan** [comment]
I run into similar problem. 

I enabled debugging and I see that when saving, am getting an insert error:

```
MongoError: Btree::insert: key too large to index, failing 
```
You can further see in the error (full error below) the index that causes the insert error (`CM_DATA.datafills_versions.$site_1`)

I checked the collection and it is created with an index on all the field in the versioned schema (I am not sure where it happens though as I don't see it in the code). 

When I removed the specified index, consequent saves do insert into the versioning collection.

I am wondering what for there is an index on all the fields and whether it is really necessary... Currently, I don't see any change tracking or anything like that which requires to do queries (searches) on all fields.

If indeed indexing on all (most) of the fields is necessary, maybe it is possible to exclude some fields through the options...

```
mongoose:version MongoError: Btree::insert: key too large to index, failing CM_DATA.datafills_versions.$site_1 1148 { : LONG STRING VALUE HERE }
mongoose:version     at Function.MongoError.create (D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb-core\lib\error.js:31:11)
mongoose:version     at toError (D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb\lib\utils.js:114:22)
mongoose:version     at D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb\lib\collection.js:658:23
mongoose:version     at handleCallback (D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb\lib\utils.js:95:56)
mongoose:version     at D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb\lib\bulk\unordered.js:465:9
mongoose:version     at handleCallback (D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb\lib\utils.js:95:56)
mongoose:version     at resultHandler (D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb\lib\bulk\unordered.js:413:5)
mongoose:version     at D:\Documents\Work\Cellcom\CellXM\src\CellXM\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:455:18
mongoose:version     at _combinedTickCallback (internal/process/next_tick.js:73:7)
mongoose:version     at process._tickCallback (internal/process/next_tick.js:104:9) +0ms
```
