### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by hydrotik** [saintedlama/mongoose-version#6]
/pathtoproject/myproject/node_modules/mongoose-version/node_modules/mongoose/lib/schema/array.js:50
    this.caster = new caster(null, castOptions);
                  ^
TypeError: object is not a function
    at new SchemaArray (/pathtoproject/myproject/node_modules/mongoose-version/node_modules/mongoose/lib/schema/array.js:50:19)
    at Function.Schema.interpretAsType (/pathtoproject/myproject/node_modules/mongoose-version/node_modules/mongoose/lib/schema.js:338:12)
    at Schema.path (/pathtoproject/myproject/node_modules/mongoose-version/node_modules/mongoose/lib/schema.js:293:29)
    at Schema.add (/pathtoproject/myproject/node_modules/mongoose-version/node_modules/mongoose/lib/schema.js:208:12)
    at new Schema (/pathtoproject/myproject/node_modules/mongoose-version/node_modules/mongoose/lib/schema.js:70:10)
    at Object.module.exports [as array](/pathtoproject/myproject/node_modules/mongoose-version/lib/strategies/array.js:11:23)
    at module.exports (/pathtoproject/myproject/node_modules/mongoose-version/lib/version.js:22:33)
    at Schema.plugin (/pathtoproject/myproject/node_modules/mongoose/lib/schema.js:545:3)
    at module.exports (/pathtoproject/myproject/modules/cms/models/project.js:102:19)
    at /pathtoproject/myproject/modules/cms/models/index.js:50:29

Using Mongoose 3.6.15

**Comment by avdaredevil** [comment]
Yes I am getting the caster error as well. It seems to be caused whenever I use the mixed type `data: {type: [[Schema.Types.Mixed]]},`. 
```
    this.caster = new caster(null, castOptions);
                  ^

TypeError: caster is not a function
```

**Comment by David-Mulder** [comment]
Seeing the same thing caused by: `, versions : [clonedSchema]`

**Comment by avdaredevil** [comment]
@david-mulder try `versions: [clonedSchema.schema]`
